version: "3.8"

services:
  short-url-backend-service:
    image: short-url-backend
    container_name: short-url-backend-container
    env_file:
      - ./.env
    networks:
      - short-url-network
    ports:
      - "3000:3000"
    depends_on:
      - mongo-service

  mongo-service:
    image: mongo
    container_name: mongo-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
    networks:
      - short-url-network

networks:
  short-url-network:

volumes:
  mongodb: