version: "3.8"

services:
  backend:
    build: ./
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - CORS_ORIGIN="*"
      - ACCESS_TOKEN_SECRET=654b61a663198ea31604afd7
      - ACCESS_TOKEN_EXPIRY=2m
      - REFRESH_TOKEN_SECRET=654bcfa84d040be1ec289e8d
      - REFRESH_TOKEN_EXPIRY=1d
    networks:
      - primary-net
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo
    volumes:
      - mongodb:/data/db
    networks:
      - primary-net

networks:
  primary-net:

volumes:
  mongodb: